"""
backend/nigerian_layer/language_adapter.py
==========================================
Takes a plain English review generated by the LLM and rewrites it
to authentically match the target archetype's voice — Pidgin level,
slang density, sentence rhythm, and cultural reference frame.
"""

from __future__ import annotations

from backend.core import llm_client
from backend.nigerian_layer.archetypes import Archetype, ARCHETYPES


# ─── System prompt template ───────────────────────────────────────────────────

_ADAPTER_SYSTEM = """You are a Nigerian language and culture expert.
Your job is to rewrite a product or restaurant review so it sounds 100% authentic
coming from the described Nigerian persona.

Rules:
1. Keep all factual content (what they liked/disliked, rating rationale) intact.
2. Adjust the language register: mix Nigerian Pidgin English naturally with
   Standard English at the density typical for this persona.
3. Weave in 1-3 of the provided slang expressions where they fit naturally —
   do NOT force all of them in.
4. Match the review length and structure to the persona's style.
5. Do not add fake facts. Do not change the star rating.
6. The result must sound like a real Nigerian wrote it — not a caricature."""


# ─── Main adapter ─────────────────────────────────────────────────────────────

def adapt_review(
    original_review: str,
    archetype:       Archetype,
    item_name:       str,
    item_domain:     str,
    star_rating:     float,
) -> str:
    """
    Rewrite `original_review` to authentically match `archetype`'s voice.
    Returns the adapted review text.
    """
    slang_sample = ", ".join(f'"{s}"' for s in archetype.slang_pool[:5])

    prompt = f"""
PERSONA: {archetype.name}
Description: {archetype.description}
Review style: {archetype.review_style}
Sample slang expressions (use 1-2 that fit naturally): {slang_sample}

ITEM: {item_name} ({item_domain})
STAR RATING: {star_rating:.1f} / 5.0

ORIGINAL REVIEW (rewrite this, do not change the facts):
\"\"\"{original_review}\"\"\"

Write the adapted review now. Output ONLY the review text — no label, no preamble.
""".strip()

    adapted = llm_client.chat(
        messages=[{"role": "user", "content": prompt}],
        system=_ADAPTER_SYSTEM,
        temperature=0.75,
        max_tokens=400,
    )
    return adapted.strip()


# ─── Batch adapter ────────────────────────────────────────────────────────────

def adapt_reviews_batch(
    reviews:     list[dict],   # each: {text, item_name, item_domain, rating}
    archetype:   Archetype,
) -> list[str]:
    """Adapt a batch of reviews for the same archetype."""
    return [
        adapt_review(
            original_review=r["text"],
            archetype=archetype,
            item_name=r.get("item_name", "item"),
            item_domain=r.get("item_domain", ""),
            star_rating=r.get("rating", 3.0),
        )
        for r in reviews
    ]


# ─── Rating language helper ───────────────────────────────────────────────────

def rating_to_naija_phrase(rating: float, archetype: Archetype) -> str:
    """Return a culturally appropriate rating summary phrase."""
    if rating >= 4.5:
        phrases = {
            "sapa_student":     "e choke! this one na 10/10 for the price",
            "hustling_corper":  "e come correct, no dulling",
            "working_class":    "consistent and reliable, I go dey come back",
            "tech_bro":         "vibe on point, the experience dey functional",
            "omo_landlord":     "it finally met my standard — rare achievement",
            "naija_mama":       "e sweet well well, the cook sabi their work",
        }
    elif rating >= 3.5:
        phrases = {
            "sapa_student":     "e dey ok for the price, I nor complain",
            "hustling_corper":  "e decent, I fit come back",
            "working_class":    "good enough, does the job",
            "tech_bro":         "it works, has potential",
            "omo_landlord":     "average at best, room for serious improvement",
            "naija_mama":       "e nor bad but my own better",
        }
    elif rating >= 2.5:
        phrases = {
            "sapa_student":     "e manage am but e nor worth the stress",
            "hustling_corper":  "abeg do better, this one no convince me",
            "working_class":    "disappointing, won't be rushing back",
            "tech_bro":         "too many bugs in the experience",
            "omo_landlord":     "highly disappointing for the price point",
            "naija_mama":       "the cook nor try at all",
        }
    else:
        phrases = {
            "sapa_student":     "even with sapa I nor come here again",
            "hustling_corper":  "this one don traumatise me",
            "working_class":    "absolutely not worth it",
            "tech_bro":         "hard no, would not deploy this experience",
            "omo_landlord":     "an embarrassment — I want my money back",
            "naija_mama":       "abeg close this place, the ancestors dey cry",
        }

    arch_key = next(
        (k for k, a in ARCHETYPES.items() if a.name == archetype.name),
        "working_class"
    )
    return phrases.get(arch_key, phrases.get("working_class", "it was fine"))
